query AllProposals {
    proposal {
        allProposals {
            id
            createTime
            changeTime
            status
            clientId
            carId
            userId
            proposalReason
            technicalInspectionResult
            recomendedWork
            completedWork
        }
    }
}
