query ProposalById($id: String!) {
    proposal {
        proposalById(id: $id) {
            id
            createTime
            changeTime
            status
            clientId
            carId
            userId
            proposalReason
            technicalInspectionResult
            recomendedWork
            completedWork
        }
    }
}
